/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.auto_mcderpvqcs.db_levelcheck.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.manager.ExportedFileManager;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.auto_mcderpvqcs.db_levelcheck.TableWithoutPk;
import com.auto_mcderpvqcs.db_levelcheck.TableWithoutPkId;
import com.auto_mcderpvqcs.db_levelcheck.service.TableWithoutPkService;


/**
 * Controller object for domain model class TableWithoutPk.
 * @see TableWithoutPk
 */
@RestController("DB_LevelCheck.TableWithoutPkController")
@Api(value = "TableWithoutPkController", description = "Exposes APIs to work with TableWithoutPk resource.")
@RequestMapping("/DB_LevelCheck/TableWithoutPk")
public class TableWithoutPkController {

    private static final Logger LOGGER = LoggerFactory.getLogger(TableWithoutPkController.class);

    @Autowired
	@Qualifier("DB_LevelCheck.TableWithoutPkService")
	private TableWithoutPkService tableWithoutPkService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new TableWithoutPk instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TableWithoutPk createTableWithoutPk(@RequestBody TableWithoutPk tableWithoutPk) {
		LOGGER.debug("Create TableWithoutPk with information: {}" , tableWithoutPk);

		tableWithoutPk = tableWithoutPkService.create(tableWithoutPk);
		LOGGER.debug("Created TableWithoutPk with information: {}" , tableWithoutPk);

	    return tableWithoutPk;
	}

    @ApiOperation(value = "Returns the TableWithoutPk instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TableWithoutPk getTableWithoutPk(@RequestParam("pkid") Integer pkid, @RequestParam("stringcol") String stringcol, @RequestParam("charcol") String charcol) {

        TableWithoutPkId tablewithoutpkId = new TableWithoutPkId();
        tablewithoutpkId.setPkid(pkid);
        tablewithoutpkId.setStringcol(stringcol);
        tablewithoutpkId.setCharcol(charcol);

        LOGGER.debug("Getting TableWithoutPk with id: {}" , tablewithoutpkId);
        TableWithoutPk tableWithoutPk = tableWithoutPkService.getById(tablewithoutpkId);
        LOGGER.debug("TableWithoutPk details with id: {}" , tableWithoutPk);

        return tableWithoutPk;
    }



    @ApiOperation(value = "Updates the TableWithoutPk instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TableWithoutPk editTableWithoutPk(@RequestParam("pkid") Integer pkid, @RequestParam("stringcol") String stringcol, @RequestParam("charcol") String charcol, @RequestBody TableWithoutPk tableWithoutPk) {

        tableWithoutPk.setPkid(pkid);
        tableWithoutPk.setStringcol(stringcol);
        tableWithoutPk.setCharcol(charcol);

        LOGGER.debug("TableWithoutPk details with id is updated with: {}" , tableWithoutPk);

        return tableWithoutPkService.update(tableWithoutPk);
    }


    @ApiOperation(value = "Deletes the TableWithoutPk instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteTableWithoutPk(@RequestParam("pkid") Integer pkid, @RequestParam("stringcol") String stringcol, @RequestParam("charcol") String charcol) {

        TableWithoutPkId tablewithoutpkId = new TableWithoutPkId();
        tablewithoutpkId.setPkid(pkid);
        tablewithoutpkId.setStringcol(stringcol);
        tablewithoutpkId.setCharcol(charcol);

        LOGGER.debug("Deleting TableWithoutPk with id: {}" , tablewithoutpkId);
        TableWithoutPk tableWithoutPk = tableWithoutPkService.delete(tablewithoutpkId);

        return tableWithoutPk != null;
    }


    /**
     * @deprecated Use {@link #findTableWithoutPks(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of TableWithoutPk instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<TableWithoutPk> searchTableWithoutPksByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering TableWithoutPks list by query filter:{}", (Object) queryFilters);
        return tableWithoutPkService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of TableWithoutPk instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<TableWithoutPk> findTableWithoutPks(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering TableWithoutPks list by filter:", query);
        return tableWithoutPkService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of TableWithoutPk instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<TableWithoutPk> filterTableWithoutPks(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering TableWithoutPks list by filter", query);
        return tableWithoutPkService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportTableWithoutPks(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return tableWithoutPkService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @RequestMapping(value = "/export", method = {RequestMethod.POST}, consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportTableWithoutPksAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = TableWithoutPk.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> tableWithoutPkService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of TableWithoutPk instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countTableWithoutPks( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting TableWithoutPks");
		return tableWithoutPkService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getTableWithoutPkAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return tableWithoutPkService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service TableWithoutPkService instance
	 */
	protected void setTableWithoutPkService(TableWithoutPkService service) {
		this.tableWithoutPkService = service;
	}

}