/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.auto_mcderpvqcs.db_levelcheck;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parent1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`PARENT1`")
public class Parent1 implements Serializable {

    private Integer parentId;
    private String parentCol1;
    private String parentCol2;
    private String parentCol3;

    @Id
    @Column(name = "`PARENT_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    @Column(name = "`PARENT_COL1`", nullable = true, length = 255)
    public String getParentCol1() {
        return this.parentCol1;
    }

    public void setParentCol1(String parentCol1) {
        this.parentCol1 = parentCol1;
    }

    @Column(name = "`PARENT_COL2`", nullable = true, length = 255)
    public String getParentCol2() {
        return this.parentCol2;
    }

    public void setParentCol2(String parentCol2) {
        this.parentCol2 = parentCol2;
    }

    @Column(name = "`PARENT_COL3`", nullable = true, length = 255)
    public String getParentCol3() {
        return this.parentCol3;
    }

    public void setParentCol3(String parentCol3) {
        this.parentCol3 = parentCol3;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Parent1)) return false;
        final Parent1 parent1 = (Parent1) o;
        return Objects.equals(getParentId(), parent1.getParentId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getParentId());
    }
}