/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.auto_mcderpvqcs.db_levelcheck;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class TableWithoutPkId implements Serializable {

    private Integer pkid;
    private String stringcol;
    private String charcol;

    public Integer getPkid() {
        return this.pkid;
    }

    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TableWithoutPk)) return false;
        final TableWithoutPk tableWithoutPk = (TableWithoutPk) o;
        return Objects.equals(getPkid(), tableWithoutPk.getPkid()) &&
                Objects.equals(getStringcol(), tableWithoutPk.getStringcol()) &&
                Objects.equals(getCharcol(), tableWithoutPk.getCharcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkid(),
                getStringcol(),
                getCharcol());
    }
}