/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.auto_mcderpvqcs.db_levelcheck;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * VirutalTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`VIRUTAL_TABLE`")
@IdClass(VirutalTableId.class)
public class VirutalTable implements Serializable {

    private String stringcol;
    private String charcol;

    @Id
    @Column(name = "`STRINGCOL`", nullable = true, length = 255)
    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    @Id
    @Column(name = "`CHARCOL`", nullable = true, length = 1)
    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VirutalTable)) return false;
        final VirutalTable virutalTable = (VirutalTable) o;
        return Objects.equals(getStringcol(), virutalTable.getStringcol()) &&
                Objects.equals(getCharcol(), virutalTable.getCharcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStringcol(),
                getCharcol());
    }
}